<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function getAllCategory()
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->orderBy('c.orderId')
            ->getQuery()
            ->getResult();
    }
}
